### ISSUE TITLE
[Bug] FF Wont Apply Autofill - Help!

### ISSUE THREAD

**Issue by sileeb** [Cookie-AutoDelete/Cookie-AutoDelete#1278]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

FF has its own built-in autofill feature. But it only works on some sites and not for the majority of them which is strange.  Could CAD be interfering with it? If so how do I fix this?

### To Reproduce

n/a

### Expected Behavior

n/a

### System Info - Operating System (OS)

win 10

### System Info - Browser Info

latest offical ff version

### System Info - CookieAutoDelete Version

3.6.0

**Comment by kennethtran93** [comment]
While I don't believe so, sometimes the sites configure it so that it doesn't provide autofill.  While not certain I believe the autofill data is currently not cleaned, unless the site themselves have configured their own method of capturing and storing data through localstorage / indexeddb.

**Comment by sileeb** [comment]
Appreciate the reply kenneth. So is there anything I can do on CAD or other means to fix this issue?

**Comment by kennethtran93** [comment]
If the autofill works while CAD is disabled but not while it is enabled (and triggered clean up), then you'll need to figure out (from that site) how it is being stored - if it is a cookie you'll need to figure out the specific cookie, otherwise you'll need to have the CAD configured to keep that site's cookie/indexedDB/localstorage/etc.

If you're using Containers / contextual identities, then the autofill may be compartmentalized as well.

Otherwise, nothing much you can do.

Here's normally how websites would disable autofill on fields: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion.

From another point of view, having only minor sites having autofill but not the rest may also indicate that those minor sites are storing field data somewhere else and your browser's autofill is not enabled.
