### ISSUE TITLE
Clear only on startup

### ISSUE THREAD

**Issue by ZathrasFive** [Cookie-AutoDelete/Cookie-AutoDelete#131]
Can this be set to clear cookies not on my whitelist **only** at start up? I selected "Clean Cookies from Open Tabs on StartUp" in settings but it doesn't work unless Active Mode is selected. But I don't want cookies cleaned when I close tabs, I just want it when I exit the browser.

Thanks

**Comment by ke-d** [comment]
You can do this now by adding just a wildcard (*) in the greylist as of 2.X.X. Whitelist has a greater precedence to greylist, so you can still whitelist domains that you want to keep but ALL other cookies will be deleted on startup.

**Comment by ElhemEnohpi** [comment]
@ZathrasFive if you don't want cookies automatically cleaned when you close tabs, then maybe you don't need this extension, as that's essentially the whole point of it!

Instead, if you're using Firefox, you can set "Preferences>Privacy & Security>Accept cookies from websites" and "keep until I close Firefox". All cookies will be cleared when you close Firefox. Then click "Exceptions" and add any websites you want to whitelist with "allow".

If you use "When Firefox starts: show my windows and tabs from last time", by default their cookies will be restored. If you would rather clear them instead, then set in "about:config",
"browser.sessionstore.privacy_level" to 2.

**Comment by Lusito** [comment]
@mrdokenny:
> You can do this now by adding just a wildcard (*) in the greylist as of 2.X.X

This does not work.. Cookies are still kept after restart.
I would also like to see this working.

@ElhemEnohpi: That might be possible, but is not convenient. Also, if there is an option, it should work. Currently it does not.

**Comment by Lusito** [comment]
I just noticed that greylisting * stops the clear now buttons from working, so this is NOT an option.

**Comment by ElhemEnohpi** [comment]
@Lusito I don't know what your use-case is, but ZathrasFive specifically said "I don't want cookies cleaned when I close tabs". In that case maybe installing an extension whose purpose is to have cookies cleaned when you close tabs, is less convenient than just using the browser's built-in function which already does what ZathrasFive wants. 

I just tested, and and with * in the greylist, cookies from sites were kept after I closed their tabs, and then deleted on start-up. So it works for me.

It's true that the "clean" buttons don't clean greylisted cookies, but I guess that's what I'd expect. "Clear cookies for this domain" does work if you have the tab still open, and if not, you could restart.

**Comment by Lusito** [comment]
How is it less convenient to always have to go to some deeply hidden settings page to manually manage what sites are allowed to keep cookies and which are not?

I don't keep firefox running for days. But I do close and re-open tabs every now and then (no, timeout is not an alternative, or do you want me to set it to multiple hours?). I want cookies removed on close/start or on manual execution. I want to be able to add websites to the whitelist with one or two clicks. 
I used selectivecookiedelete before, but that one is not web-extension ready.

>Also I just tested, with * in the greylist, cookies from sites were kept after I closed their tabs, and then deleted on start-up. So it works for me.

Wait, do you need to enable the automatic cleaning for that?

>It's true that the "clean" buttons don't clean greylisted cookies, but I guess that's what I'd expect.

Well, yes, a * greylist would be correct to do this, but a * greylist should never even be necessary.
Why is there an option to delete cookies on startup, if it doesn't work without automatic cleaning? Automatic cleaning already removes those cookies even before you close firefox or am I missing something here?

**Comment by ElhemEnohpi** [comment]
Right, it's difficult for me to grasp that manager buttons for the built-in cookie exceptions just don't exist anymore, since I've been using them forever. You could bookmark `about:preferences#privacy`, but yes if you need to whitelist a lot of sites, I guess it could get tedious. But there are some advantages to using the built-in cookie exceptions system. And you still need to use it if you want to block cookies.

Yes, you need to enable automatic cleaning for cookies to be automatically cleaned on startup. 

If you put * in the greylist, then no cookies are automatically cleaned when their tabs are closed. If they're on the whitelist, they're kept until they expire. Otherwise they're cleaned on the next startup, like the old system of "keep cookies until: I close Firefox". You miss out on the whole concept of auto-deleting/self-destructing cookies. But if that's what you really want, you can do it.

There's also the option "Clean Cookies from Open Tabs on Startup". That's if you leave a tab open and use "show my windows and tabs from last time". By default its cookies will also be restored, but that option lets you clean them. It's basically the same as ""browser.sessionstore.privacy_level = 2". This does clean greylisted cookies, as opposed to the "Clean, include open tabs" button which doesn't.
