### ISSUE TITLE
3rd party cookies control and HTTP/HTTPS  specifci cookies

### ISSUE THREAD

**Issue by tsunami2311** [Cookie-AutoDelete/Cookie-AutoDelete#141]
I have noticed I cant whitelist or gray list 3rd party cookies to site IF the cooking used are  specifically using HTTPS/HTTP cause you cant specify HTTP/HTTPS in it whitelist/grey list page.

### Steps for anyone to reproduce the bug
1. go to [https://store.playstation.com/#!/en-us/home/main](url)
2. Login ( 3rd party cookies must be enabled in Firefox or `https://auth.api.sonyentertainmentnetwork.com` must be whitelistd in Firefox internal whitelist for login to work.

If trying  to whitelist threw  ADDON trying to add `https://auth.api.sonyentertainmentnetwork.com` or `http://auth.api.sonyentertainmentnetwork.com`  as whitelist or gray list results in only `https://` or `http://` showing in the list and putting just `auth.api.sonyentertainmentnetwork.com` will result in the 3rd party cookie  to remain blocked.

I am coming from SDC which i think had the same issue ? when to trying whitelist  cookies threw it settings, which why I been whitelisting threw Firefox and ignoring the addon controls, i do fine this addon much my cleaner and simpler to use

### Your settings 

settings where left at defualt

Windows 10
Firefox 55.0.3
- Cookie AutoDelete  1.4.4

**Comment by mrdokenny** [comment]
HTTPS/HTTP doesn't matter as it will only look at `store.playstation.com` (without the 'HTTPS/HTTP' and 'www') for the comparison.

The problem with SDC and C-AD is that it can't save cookies from third-party cookies if a site saves them since it is impossible to code for every site.

Ex. `store.playstation.com` -> ` sonyentertainmentnetwork.com` cookies
What the algorithm can save is cookies from subdomains of `playstation.com` if you are on the `store.playstation.com`.

I would try whitelisting these to be safe:
`auth.api.sonyentertainmentnetwork.com`
`api.sonyentertainmentnetwork.com`
`sonyentertainmentnetwork.com`

In the next major version #113, you'll be able to use wildcards, which means you can just do
`*.sonyentertainmentnetwork.com`

**Comment by tsunami2311** [comment]
none of those will work for whitelisting/greylisting in  the addon, so i am assuming I must remain white listing 3rd party cookies from firefox internal whitelist system

3rd party cookies only with i allow threw firefox internal whitelist or if I set 3rd party to allow,

**Comment by tsunami2311** [comment]
side note unless i doing something wrong if i added `auth.api.sonyentertainmentnetwork.com` to firefox built whitelist, with out the HTTPS:// the cookie remians blocked and fails, which why the https:// is there

**Comment by mrdokenny** [comment]
>for years i have had 3rd party cookies disable and been whitelisting them manually threw firefox internal exclude list would be nice if the cookie addon could see and whitelist those cookies

Ah, that's different. Basically, I have no access to those with the current WebExtension APIs. See #43

**Comment by tsunami2311** [comment]
im not even gona prettend to understand what being said there, basicliy i should just expect the same behavior in regards to that? less Mozilla they self add the support? not big issue seeing i only whitelist handfull of sites threw firefox system anyway

**Comment by mrdokenny** [comment]
Since you disable all third party cookies but allow some through whitelist, you have to whitelist in FF internal cookie manager AND C-AD.

**Comment by ke-d** [comment]
Closing for inactive support issue.
