### ISSUE TITLE
Container Mode Related Bugs

### ISSUE THREAD

**Issue by mrdokenny** [Cookie-AutoDelete/Cookie-AutoDelete#41]
- [x] Adding and Removing Containers should affect the whitelist
  - Workaround is to export white/grey lists, restore default settings, reimport white/grey lists
- [x] Cookie Cleanup breaks if the extension calls browser.contextualIdentities.query() (this is relating to the above since I do caching to avoid calling that function but the cache doesn't update after a change in Containers)
  - This most likely happens the user enables "Container Mode" for the first time or Restore Default Settings then enable "Container Mode"
  - - [x] Related Bug: [1362928](https://bugzilla.mozilla.org/show_bug.cgi?id=1362928)
  - This shows up as `TypeError: cookieDomain is undefined[Learn More]` in console
  - A workaround for this is to just restart the browser

**Comment by jonathanKingston** [comment]
Hey!

So in Nightly you can now subscribe to container events which should allow for you to monitor container additions or removals. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1344519

Also as a heads up:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1389265 promises for the apis will now reject rather than resolve null and false.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1354602 containers will now be enabled for all your users as you have the permission.

I will see if I can get some debugging time on your bug you raised tomorrow.

Feel free to ask me any other container question you might have.

Thanks!
