### ISSUE TITLE
White-list by cookie name

### ISSUE THREAD

**Issue by temporaryaccount** [Cookie-AutoDelete/Cookie-AutoDelete#68]
I'd like a feature to white-list cookies by their name, or rather "host + cookie name" combination. I understand this is a feature for advanced users only (they have to view the cookies and decide that they want particular cookie but not the others).

Use cases:

1. Allow only the session id cookie, deny the other (tracking) cookies on many websites

2. Allow only the "over18" or similar cookies and deny all others

3. Allow only the [EU "accept cookies"](https://www.cookielaw.org/the-cookie-law/) cookie and deny all others

**Comment by mrdokenny** [comment]
Personally I don't have a need for this feature since this is similar to [CookieCuller](https://addons.mozilla.org/en-US/firefox/addon/cookieculler/) and this extension is leaning more towards SDC. So I'll probably won't implement this. Currently I think the code isn't designed for whitelisting certain cookie names in addition to hostnames, so it would take a significant amount of work for something I won't use. 😉 

Hopefully someone will make a port of CookieCuller because it seems very doable. Or if someone really wants this feature, they can try implementing it themselves. I might have an idea of how this might work but only if someone is willing to put the effort (as per [Contributing Code](https://github.com/mrdokenny/Cookie-AutoDelete#contributing-code)) and sending in a PR.

**Comment by temporaryaccount** [comment]
Unfortunately the CookieCuller extension is written as an old-style and soon to be deprecated XUL addon (last update was nearly 8 years ago) which will stop working with Firefox 57 and beyond. I don't think it will be very straightforward to port its code into a WebExtension addon, so [porting](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on) it would be more like redoing :-)

I have some experience in writing AddOn SDK style addons for Firefox, so please leave this issue Open for some time, and if nobody else is interested I'll try to refresh my knowledge by reading some docs about WebExtension and make a PR by myself.

**Comment by mrdokenny** [comment]
>I don't think it will be very straightforward to port its code into a WebExtension addon, so porting it would be more like redoing :-)

It would be just adding another attribute to check the cookie name. The hard work is getting it to work with the current implementation and not breaking previous functionality.

**Comment by woctezuma** [comment]
For info, [CookieKeeper](https://addons.mozilla.org/fr/firefox/addon/cookiekeeper/) (CK) is multi-process ready and does the same job as CookieCuller (CC). CK was last updated in April 2016, while CC was last updated in December 2009, as you mentioned.

**Comment by LaurentGrenet** [comment]
Yes, I confirm : this new feature **would be very great**... even if I'm not able to participate in its development (not skilled..).
Currently, I'm using excellent CookieKeeper (which does exactly that...), but this extension won't be ported in WebExtension format... and then no more available starting FFx 57 :-((

**Comment by Epicbeardman** [comment]
As a former CookieKeeper user, I would absolutely LOVE to see this feature. It kind of bothers me that my browser is storing extra cookies that it doesn't need right now, and the implementation of this feature (along with localStorage support) would really make this otherwise excellent extension feel complete.

**Comment by woctezuma** [comment]
@Epicbeardman You might want to try _[No Cookies For Old Men](https://addons.mozilla.org/firefox/addon/no-cookies-for-old-men/)_, which I find complimentary to _Cookie AutoDelete_, even though it does not fulfill your exact need. Indeed, _No Cookies For Old Men_ should help decrease the number of cookies stored by websites on the whitelist of _Cookie AutoDelete_, by demoting unnecessary cookies to session cookies.

Another feature which I like is the ability to view the cookies stored for the current website with one click:
![display of cookies with one click](https://i.imgur.com/T5rvena.png)

**Comment by YoRHa-A5** [comment]
Any news on this? I'd love to keep login cookies escpecially ^^

**Comment by ghost** [comment]
@temporaryaccount 

> I'd like a feature to white-list cookies by their name, or rather "host + cookie name" combination. I understand this is a feature for advanced users only (they have to view the cookies and decide that they want particular cookie but not the others).

Great suggestion. I'll add that I find it important for this functionality to work even after the cookie expires, so it should not be linked to its TTL anyhow.

**Comment by ghost** [comment]
Is this addon being maintained? One year passed since this issue was created.

I'm not a dev, but I imagine this issue being easy to solve. I guess the addon has access to the list of cookies, so it has to list the cookies by requesting this from the browser then showing the cookies to the user, allow to whitelist specific cookies and then delete all the others.

I'm not trying to act disrespectfully, I genuinely don't understand if this is a hard to implement issue or the devs just don't like this feature or smth else.

I have 50+ cookies from youtube.com and I have to keep them, or otherwise with this feature implemented I could just keep 1 or 2 which are mandatory for authentication. : (

In any case thanks a lot devs for the great work you are doing! Looking forward to seeing this feature coming to life one day.

**Comment by temporaryaccount** [comment]
@Zig-03 

As much as I'd like to see this feature implemented one day, we have to remember that open source project, in most cases, are being developed by volunteer individuals for free, in their own free time, and the authors don't owe us anything.

If the authors don't prioritize this issue then we'll have to either implement it by ourselves and offer the code as a pull request, or maybe crowdfund to sponsor this request, so the developers would be motivated.

**Comment by ke-d** [comment]
@Zig-03 

I'm quite busy during this summer, but I'll probably come back when the WebExtension API has matured a bit like adding an API for clearing IndexedDB by hostname.

> I'm not trying to act disrespectfully, I genuinely don't understand if this is a hard to implement issue or the devs just don't like this feature or smth else.

There's still the issue of figuring out of what to do with localstorage cleaning in this case since it doesn't have a granular API (it's delete all or nothing at this point) like with cookies.

Right now it's a pretty good assumption that if a user whitelists a site then they don't want the localstorage for that site to be deleted.

If the user whitelist certain cookies, then you don't know if the user wants localstorage to be deleted or not.

This issue would probably have to go along with #341 in order to make sense.

**Comment by ghost** [comment]
hey @mrdokenny 
thanks for taking your time to reply here, appreciated. Again, thanks a lot for your work, I'm enjoying your extension a lot :)

I found an extension that already can do it ([link here ](https://github.com/Rob--W/cookie-manager)) with a little CSS I guess you'd be able to integrate it, no? At least maybe as a "temporary fix".

**Comment by ke-d** [comment]
![image](https://user-images.githubusercontent.com/17077613/50543543-03e44b00-0b90-11e9-8743-091cefe987aa.png)

WIP: Things are subject to change

**Comment by madduck** [comment]
Wow, I can't wait!

**Comment by ke-d** [comment]
Feel free to try 3.0.0b1 for this feature and let me know what you guys think. :)
Might be some bugs and all but should be mostly stable.

**Comment by ghost** [comment]
> Feel free to try 3.0.0b1

How do we do this?

Oh, I found it https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases I'll report back once I test it.

**Comment by temporaryaccount** [comment]
Looks marvellous. Thank you, Kenny Do! Or should I say Mr. Kenny Do :)

**Comment by grenzor** [comment]
@mrdokenny 

Looks nice, will try it out. I'm wondering how the UI deals with sites that set a lot of cookies seems like it could get very long in the dashboard. Does it show like the first 5 cookies then user clicks some dropdown arrow to see them all? Also could get cramped in both dashboard/popup if IndexedDB/other storage cleaning is introduced in the future.

**Comment by ke-d** [comment]
@grenzor  
>I'm wondering how the UI deals with sites that set a lot of cookies seems like it could get very long in the dashboard. Does it show like the first 5 cookies then user clicks some dropdown arrow to see them all?

It's now a scrolling list that shows 5 cookie names at a time.

>Also could get cramped in both dashboard/popup if IndexedDB/other storage cleaning is introduced in the future.

Right now, there's no way to list individual items from other storage data yet alone to clear them individually.

**Comment by ghost** [comment]
@mrdokenny seems to work great, thanks a lot!

**Comment by ke-d** [comment]
@Zig-03 No problem. 

Closing since 3.0.0 is out.
