### ISSUE TITLE
Doesn't work with Firefox's privacy.firstparty.isolate = true

### ISSUE THREAD

**Issue by nkestrel** [Cookie-AutoDelete/Cookie-AutoDelete#75]
With `privacy.firstparty.isolate = true` the cookie count is always zero and cookies are not deleted despite notification claiming that they were.

Details about the setting:

https://bugzilla.mozilla.org/show_bug.cgi?id=565965

https://www.torproject.org/projects/torbrowser/design/#identifier-linkability

**Comment by mrdokenny** [comment]
I used that setting before with C-AD months ago, so I'm pretty sure this is a browser bug and Mozilla has to fix it. I'll do some more testing before marking as wontfix/cantfix.

**Comment by mrdokenny** [comment]
Yep, that setting sure breaks C-AD and this error might be related since its the only one that appears. 

`TypeError: parentDocShell.getDocShellEnumerator is not a function[Learn More] tab.js:62:23`

So it seems to be a problem with the WebExtension Cookie API with that setting.

**Comment by nkestrel** [comment]
Upstream [Bug 1381197](https://bugzilla.mozilla.org/show_bug.cgi?id=1381197).

**Comment by mrdokenny** [comment]
@nkestrel Hmm isn't the problem (at least for C-AD primary functionally) is browser.cookies.remove() doesn't work?

Related code:
https://github.com/mrdokenny/Cookie-AutoDelete/blob/master/src/services/CleanupService.js#L59

**Comment by nkestrel** [comment]
I broadened the scope of the bug title, I just found cookies.getAll easier to categorize the failure.

**Comment by WagnerGMD** [comment]
In fact, I was looking to replace these addons :
- [Shim Storage](https://addons.mozilla.org/en-US/firefox/addon/shim-storage/)
- [Self-Destructing Cookies](https://addons.mozilla.org/fr/firefox/addon/self-destructing-cookies/)
- and I want to clear the file **SiteSecurityServiceState.txt** (the leak **HSTS**)

But (the addon) [CAD](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/) (CookieAutoDelete_v 1.4.1) doesn't have these functions (at least not for the moment). And it doesn't seem to work fine...

`pref("privacy.firstparty.isolate",true);`
Because I had check a few times and no, it doesn't seem to be cause by this settings.
Despite the notification, no the cookies aren't really remove (by CAD). I'm still able to see them on the page **about:preferences#privacy** (via the button **Show Cookies...**) and another reason, it's because I'm able to remove them with [CookieKeeper](https://addons.mozilla.org/en-US/firefox/addon/cookiekeeper/).

**Comment by mrdokenny** [comment]
@WagnerGMD Try the troubleshooting steps I posted on the addon page, otherwise make another issue.

**Comment by Thorin-Oakenpants** [comment]
@WagnerGMD Are you in Private Browsing Mode?

**Comment by WagnerGMD** [comment]
On the moment, I didn't notice the troubleshooting.
```
pref("network.cookie.lifetimePolicy",2);
pref("network.cookie.cookieBehavior",1);
```
But no nothing has changed once I had reset the both settings. And I don't think it cause by the profil (from scratch a few times and yes I had restart the browser).

No @Thorin-Oakenpants I don't use it often.

**Comment by Thorin-Oakenpants** [comment]
Can you double check that @bendover22 , because `privacy.firstparty.isolate.restrict_opener_access` at `true` is the harder restriction and `false` loosens it (for some of cross domain login issues) - see https://bugzilla.mozilla.org/show_bug.cgi?id=1319773#c22

**Comment by curiosity-seeker** [comment]
I've tried it for FF54 and FF57 Nightly with both `privacy.firstparty.isolate`and `privacy.firstparty.isolate.restrict_opener_access`set to `true`. C-AD reports cookies as being deleted but they are **not** according to `about:preferences#privacy`.

**Comment by mrdokenny** [comment]
Is SDC affected by `privacy.firstparty.isolate` as well?

**Comment by curiosity-seeker** [comment]
Just tried SDC, and it seems that it is affected, too. In other words this is not necessarily a webextension related problem.

**Comment by WagnerGMD** [comment]
I didn't understand on the moment... So I just will add one reminder : SDC is aka Self-Destructing Cookies.

~PS : There is a particular syntax (markdown) for acronyme on GitHub ? GitHub can improve the toolbar... That's why no I don't have a clue...

**Comment by bendover22** [comment]
> _Can you double check that @bendover22 , because_ 
Sorry, no.  I had to remove C-AD because it allows all sites to set 1st party cookies.
But I checked the pref privacy.firstparty.isolate.restrict_opener_access:true - pretty well while C-AD was installed & "privacy.firstparty.isolate" was false. 

If Kenny wants me to test out some C-AD change  (in Fx, Fx ESR, or Tor Browser), I'll be happy to help.  I'd probably create a clean profile for testing purposes.

It's possible some other addon gave me different results w/ **"privacy.firstparty.isolate.restrict_opener_access"** than you, but it's kind of a moot point for me.  At least until C-AD can immediately delete cookies (or block), WHEN no cookie exception is stored for a site.  If that's not possible or "won't fix,"  like others are saying - when Fx 57 breaks all legacy addons, I'll probably use an Fx fork that supports them.  

Possible that Mozilla poo-pooed in their nest,  deciding NOT to allow existing legacy addons to work & just require new ones to use web ext. (when almost NO web ext. replacements are ready).
Since Netscape, millions of users never wanted 1st party cookies allowed by default.  It's more of an issue today, because of sites sharing data w/ 3rd parties (not just cookies), and because many sites are owned by the same entity.
 
Re:  https://bugzilla.mozilla.org/show_bug.cgi?id=1319773#c46 - says:

> privacy.firstparty.isolate:true + privacy.firstparty.isolate.restrict_opener_access:true **(Tor defaults)**

Both prefs are not Tor Browser defaults [not recently].
In TBB 7.0.4, only "privacy.firstparty.isolate:true " is present & default = True (in Linux).

**Comment by mrdokenny** [comment]
>FWIW, I understand they're different, legacy addons vs. C-AD, but in Fx 55 with both of these prefs - "privacy.firstparty..." ** set = true**, both Cookie Monster 1.3.4.8 & Clear Console 1.13 (by Rejah Rehim) delete cookies just fine. 

It's possible that Cookie Monster is going through the `cookies.sqlite` file and deleting the cookies using SQL, since legacy extensions do have access to file storage. The WebExtension APIs are just a way to standardize stuff so that people don't do their own way of "deleting" cookies

>But since Mozilla "based cookie API on Chrome's API," you'd think most bugs would be worked out. Or not.

Chrome doesn't have first party isolation, so it's pretty much a new case for Mozilla.

**Comment by Thorin-Oakenpants** [comment]
@mrdokenny  `<snip name dropping>` about FPI locking extensions from handling persistent data (think cookies, dom storage, indexeddb etc) ... and we have some traction: see https://bugzilla.mozilla.org/show_bug.cgi?id=1362834#c30  (The FPI cookie ticket is [1381197](https://bugzilla.mozilla.org/show_bug.cgi?id=1381197) but 1362834 re internal google cookies is where they're talking overall permissions and whatnot). Feel free to chime in on the bugzillas and get what we need - maybe even access to PB Mode cookies (although in future PB mode is expected to use FPI)

**Comment by mrdokenny** [comment]
@Thorin-Oakenpants  Good to hear.

>maybe even access to PB Mode cookies (although in future PB mode is expected to use FPI)

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/139#issuecomment-328265232

Seems like Chrome gives access to PB cookies

**Comment by gryzor2** [comment]
So, OK, this happens fundamentally because of a firefox bug.
Anyway, the result is very bad for the user. For months, I've received popups from cookie delete which were stating how many cookies it was deleting. So, because of this [firefox] bug, the extension was lying to me.

Is it possible to add a test routine, like picking a cookie before it is deleted, and checking after deletion whether it is still present? If the cookie is still present, this could warn the user that at least something is wrong (RTFM link) instead of poping up "cookies deleted", or after poping it out. This would give the user a chance. And it would detect other future similar occurrences of the same problem.

The current state of things, with this firefox bug, is that the user believes to be safe, and isn't. Worst possible state.

My last sentence needs to be : thanks for this great extension.

**Comment by jingofett** [comment]
Should I just disable `privacy.firstparty.isolate` ?

**Comment by gryzor2** [comment]
Yes, to turn around the bug, you need to do the following 
1. Make sure you disable `privacy.firstparty.isolate` in `about:config`
2. Delete all existing cookies by hand

Then the extension works like a charm for all newly created cookies.

**Comment by thiswillbeyourgithub** [comment]
Can anyone tell me which is better for privacy ? Should I rather activate isolation or use your (otherwise great) addon to clean them ?

**Comment by curiosity-seeker** [comment]
@thiswillbeyourgithub : I can't definitely answer your question. But: As an alternative you can disable `privacy.firstparty.isolate` and install the add-on [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) instead. When its Automatic Mode is enabled (which is the default) it opens **every** tab in a _temporary_ [container](https://support.mozilla.org/en-US/kb/containers). This seems to work very well. And all cookies are deleted by C-AD as expected. Cool!

**Comment by rue** [comment]
Given that looks like the fix is in [Firefox 58](https://hacks.mozilla.org/2017/11/new-in-firefox-58-developer-edition/) (Beta channel as of today at least), what exactly is the status of this bug?

**Comment by nkestrel** [comment]
@rue That article is referring to extensions being able to toggle on/off the `privacy.firstparty.isolate` setting, it does not mean they can manage isolated cookies. [Bug 1381197](https://bugzilla.mozilla.org/show_bug.cgi?id=1381197) dictates the current status for this bug (not fixed).

**Comment by Thorin-Oakenpants** [comment]
FYI: [1381197](https://bugzilla.mozilla.org/show_bug.cgi?id=1381197) - resolved fixed 59 an hour ago

**Comment by thiswillbeyourgithub** [comment]
@Thorin-Oakenpants I'm not sure I understand, the fix will appear in firefox 59 only and not before ? So in a few months ?

**Comment by Thorin-Oakenpants** [comment]
@thiswillbeyourgithub unless they backport the patches to 58, correct.

Nightly (currently 59) is where they add new features. Stable (currently 57) only gets patches for critical items (such as the timing mitigations in 57.0.4 against Spectre).

When Nightly moves to 60, 59 becomes the beta channel. And again, more testing, at least a release cycle's worth. When 59 becomes stable, then there should be no issues.

This pattern also gives devs like mrdokenny to start coding and testing so his fixes will be ready in time. So yeah, [Release Calendar](https://wiki.mozilla.org/RapidRelease/Calendar) says we can expect this on March 13

**Comment by ke-d** [comment]
I added the fixes necessary for FPI to work in CAD 2.1.0b3 and the latest nightly 59+. 

When flipping the FPI setting in `about:config`, please restart the browser (or just CAD).

The `privacy` API is requested in order to detect whether the user has enabled FPI.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy/websites

Feedback is welcome as there is so many interactions between different browser settings and CAD settings that it's impossible to test for everything.

**Comment by overdodactyl** [comment]
Hi @mrdokenny, thank you for your quick work, it's really appreciated!

I'm running into a problem when trying to delete cookies in FPI.  I've tried flipping the FPI flag on/off, restarting, uninstalling and reinstalling CAD.

When trying to delete a cookie, I get this message via the debugging console:

`Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set.`

I seem to have this same problem in a new profile.

Browser Version:  59.0a1 (2018-01-06) (64-bit)
OS: macOS
CAD Version:2.1.0b3

Let me know if there's anything I can do to help diagnose the issue or if there's more info I can provide.  

Thanks again

**Comment by ke-d** [comment]
@overdodactyl 
>Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set.

I forgot to add that for the `Clear all cookies for this domain`. But cookie cleanup should still work.

I'll look into it more.
 
Edit: Also sometimes the cookie manager in FF doesn't update right away. So are you still seeing notifications that it gets deleted?

**Comment by overdodactyl** [comment]
>But cookie cleanup should still work.

Ah, perfect! That is working for me.

>So are you still seeing notifications that it gets deleted?

I'm not seeing notifications in the first case where the error came up, however I do get them when using the cookie clean up

**Comment by bluegrover** [comment]
OK, did a brief testing in FF59b3 and it seems to be working. When pfi = true is set then CAD does delete cookies (& notifies you) you eg. when closing a Tab

**Comment by prog-amateur** [comment]
I have received the same error message than @overdodactyl : 
`Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set.` 
In https://www.privacytools.io/#about_config , they clearly insist to keep `privacy.firstparty.isolate = true`, arguing that this allows to prevent tracking across different domains. So I didn't switch the FPI into OFF. 

**My question is :** 
-> as the bug is solved in Firefox 59 (so we have to wait for it), can I meanwhile use the following countermeasure : 
- keep FPI set to true ?
- install Temporary Containers web extension ?

Thank you very much for your kind reply.

**Comment by ke-d** [comment]
@prog-amateur The point is that FPI=true will prevent *any* extension from cleaning cookies. So even with Temporary Containers, they won't get deleted based off this [comment](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/75#issuecomment-348792910).

**Comment by ke-d** [comment]
Also in the new version 2.1.1, CAD will show notifications telling you if you have FPI on only if you have FF 58 since the setting to access the value of FPI is in 58+.

**Comment by prog-amateur** [comment]
Thank you very much for your quick feedback, in that case, I have disabled FPI. 
Does it means, after FF 58, I will be able to switch FPI on True AND use CAD ?  
Thank you !

**Comment by ke-d** [comment]
>Does it means, after FF 58, I will be able to switch FPI on True AND use CAD ?

Yes.

**Comment by thiswillbeyourgithub** [comment]
Sorry guys but to be clear, *after 58* means 59 and not *after 58 is out*. Right ?

**Comment by bonanza123** [comment]
For me, on FF 59b3, FPI=true still seems to block clearing cookies by CAD (not deletion popups and not deleted cookies). @bluegrover is there some trick I'm missing?

**Comment by deepsweet** [comment]
Works just flawlessly for me with 59b3 without any containers and with `privacy.firstparty.isolate = true`.

**Comment by jmozmoz** [comment]
For me cookies are not deleted, if firstparty.isolate is true in Firefox 59.0beta4

**Comment by ke-d** [comment]
@jmozmoz Try deleting your cookies and restarting your browser.

**Comment by jmozmoz** [comment]
> Try deleting your cookies and restarting your browser.

Thank you, this worked.

**Comment by prog-amateur** [comment]
Hi I have the same issue with Android version 58.0.2, I have a notification to turn off FPI despite deletingcookiesand restart. Please, could you check ?
Thank you very mucj

**Comment by cherti** [comment]
@prog-amateur 
The relevant fix is included in Firefox 59 onwards. You will have to wait a bit until the 59-release propagated to Android.

**Comment by prog-amateur** [comment]
@cherti : OK I see, thank you very much for your feedback !

**Comment by ke-d** [comment]
Closing as Firefox 59 is out.
